#!/bin/bash
call=$1
arg1=$2
arg2=$3
directory=$(which jbscripts)_dir/

if [ -z $call ]; then
  echo 'No call given'
  echo 'Valid calls: wgs'
  exit
fi

if [ $call == 'wgs' ]; then
  echo 'Processing files as WGS data...'
  ${directory}process_plot-wgs.sh $arg1 $arg2
elif [ $call == 'dance' ]; then
  echo 'we gonna dance'
elif [ $call == 'boogy' ]; then
  echo 'we gonna boogy'
else
  echo "Invalid call: $call"
  echo 'Valid calls: wgs'
fi
