#!/bin/bash
call=$1
arg1=$2
arg2=$3
arg3=$4
directory=$(which jbscripts)_dir/

if [ -z $call ]; then
  echo 'No call given'
  echo 'Valid calls: wgs'
  exit
fi

if [ $call == 'wgs' ]; then
  echo 'Processing files as WGS data...'
  ${directory}process_plot-wgs.sh $arg1 $arg2
  ${directory}trim_process_plot-wgs.sh $arg1 $arg2 $arg3
elif [ $call == 'rna-seq' ]; then
  echo 'Coming soon'
elif [ $call == 'ssrna-seq' ]; then
  echo 'Maybe some day'
else
  echo "Invalid call: $call"
  echo 'Valid calls: wgs'
fi
